[package]
name = "gptee"
version = "0.3.3"
edition = "2021"
rust-version = "1.67"
authors = ["Roger Zurawicki <roger@zura.wiki>"]
categories = ["development-tools"]
keywords = ["openai", "ai", "gpt"]
description = "output from a language model using standard input as the prompt"
readme = "README.md"
license = "MIT"
homepage = "https://github.com/zurawiki/gptee"
repository = "https://github.com/zurawiki/gptee"

[[bin]]
name = "gptee"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.70"
async-openai = "0.10.0"
backoff = { version = "0.4.0", features = ["tokio"] }
clap = { version = "4.1.11", features = ["derive"] }
futures = "0.3.27"
tempfile = "3.4.0"
tiktoken-rs = "0.3.3"
tokio = {version = "1.26.0", features = ["full"]}
tracing-subscriber = { version = "0.3.16", features = ["env-filter"]}
